manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: beatnik
      url-base: https://github.com/beatnikau
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: nice_view_beat
      remote: beatnik
      revision: v0.3.0
  self:
    path: config
